version: '3.8'

services:
  github-runner:
    build:
      context: .
      args:
        RUNNER_VERSION: ${RUNNER_VERSION:-2.311.0}
        UBUNTU_VERSION: ${UBUNTU_VERSION:-24.04}
    environment:
      - REPO_URL=${REPO_URL}
      - REGISTRATION_TOKEN=${REGISTRATION_TOKEN}
      - RUNNER_NAME=${RUNNER_NAME:-docker-runner}
      - RUNNER_LABELS=${RUNNER_LABELS:-docker,linux}
      - EPHEMERAL=${EPHEMERAL:-false}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    privileged: true